apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smoke-app
  namespace: smoke-app
spec:
  ingressClassName: haproxy
  rules:
    - host: smoke.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smoke-app
                port:
                  number: 80
