ansible_connection: amazon.aws.aws_ssm
ansible_aws_ssm_region: us-east-1
ansible_aws_ssm_timeout: 60
ansible_aws_ssm_bucket_name: k8s-hardway-ansible-ssm-022671037904
cluster_name: k8s-hardway
kubernetes_service_cidr: 172.16.0.0/24
kubernetes_service_ip: 172.16.0.1
cluster_dns_ip: 172.16.0.10
pod_cidr: 10.0.0.0/16
encryption_key: "EmChrOahiJ+gRs9yoiiJOpSztf7MumJm+AUp9EB07uY="
